
DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  id serial PRIMARY KEY,
  date_posted DATE,
  note TEXT NOT NULL
) 

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
